# # Tulqin Muxtorov CreatedBy 2024-01-19
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: ${DOCKER_PROJECT_NAME}_gitlab
    restart: unless-stopped
    ports:
      - '8011:80'
      - '443:443'
      - '8025:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '2gb'

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
